Repository yahoo/fili, pull requests merged in 2018-04, with the labels that each got.

#649 Correct exception message & add missing tests
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/util/StreamUtils.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/ErrorMessageFormat.java
  fili-core/src/test/groovy/com/yahoo/bard/webservice/util/StreamUtilsSpec.groovy
Labels: BUG, MERGEABLE, REVIEWABLE, TESTING

#663 Adds a factory for building `ResponseProcessor`.
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/application/AbstractBinderFactory.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/DataServlet.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/responseprocessors/ResponseProcessorFactory.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/responseprocessors/ResultSetResponseProcessorFactory.java
Labels: MERGEABLE, REVIEWABLE

#610 Enhance generic example
  fili-core/src/main/java/com/yahoo/bard/webservice/data/config/metric/MetricInstance.java
  fili-core/src/main/java/com/yahoo/bard/webservice/util/Utils.java
  fili-generic-example/src/main/java/com/yahoo/wiki/webservice/data/config/auto/DataSourceConfiguration.java
  fili-generic-example/src/main/java/com/yahoo/wiki/webservice/data/config/auto/DruidNavigator.java
  fili-generic-example/src/main/java/com/yahoo/wiki/webservice/data/config/auto/TableConfig.java
  fili-generic-example/src/main/java/com/yahoo/wiki/webservice/data/config/dimension/GenericDimensionConfigs.java
  fili-generic-example/src/main/java/com/yahoo/wiki/webservice/data/config/metric/GenericMetricLoader.java
  fili-generic-example/src/main/java/com/yahoo/wiki/webservice/data/config/table/GenericTableLoader.java
  fili-generic-example/src/test/java/com/yahoo/wiki/webservice/data/config/auto/StaticWikiConfigLoader.java
  fili-wikipedia-example/src/main/java/com/yahoo/wiki/webservice/data/config/metric/WikiMetricLoader.java
Labels: NEED REBASE, REVIEWABLE

#633 Replace Old gmaven with New gmavenplus
  pom.xml
Labels: MERGEABLE

#665 use 'maven-enforcer-plugin' instead of maven version prerequisites (i…
  fili-core/pom.xml
  fili-generic-example/pom.xml
  fili-navi/pom.xml
  fili-security/pom.xml
  fili-system-config/pom.xml
  fili-wikipedia-example/pom.xml
  fili/pom.xml
  pom.xml
Labels: MERGEABLE

#677 Avoid casting to generate SimplifiedIntervalList
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/web/handlers/VolatileDataRequestHandler.java
Labels: DEBUG, REVIEWABLE

#678 Avoid casting to generate SimplifiedIntervalList
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/web/handlers/VolatileDataRequestHandler.java
Labels: DEBUG, REVIEWABLE
