Repository yahoo/fili, pull requests merged in 2018-03, with the labels that each got.

#583 change comment from 'form' to 'from'
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/DimensionCacheLoaderServlet.java
Labels: DOCS, MERGEABLE

#613 Corrected behavior of show=none to support silent dimension columns.
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/web/JsonApiResponseWriter.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/ResponseData.java
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/endpoints/DimensionShowClauseNoneCsvDataServletSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/endpoints/DimensionShowClauseNoneDataServletSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/endpoints/DimensionShowClauseNoneJsonApiDataServletSpec.groovy
Labels: MERGEABLE

#645 Add config to ignore partial/volatile intervals and cache everything in cache V2
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/config/BardFeatureFlag.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/responseprocessors/CacheV2ResponseProcessor.java
  fili-core/src/test/groovy/com/yahoo/bard/webservice/config/FeatureFlagRegistrySpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/responseprocessors/CacheV2ResponseProcessorSpec.groovy
Labels: MERGEABLE

#641 Add Missing perPage Param
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/web/AbstractResponse.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/JobsServlet.java
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/JsonResponseSpec.groovy
Labels: DEBUG, MERGEABLE

#635 Fix a Minor Javadoc
  fili-core/src/main/java/com/yahoo/bard/webservice/util/Either.java
Labels: DOCS, MERGEABLE

#606 Annotate Functional Interface
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/async/jobs/jobrows/JobRowBuilder.java
  fili-core/src/main/java/com/yahoo/bard/webservice/async/workflows/AsynchronousWorkflowsBuilder.java
  fili-core/src/main/java/com/yahoo/bard/webservice/data/config/dimension/DimensionLoader.java
  fili-core/src/main/java/com/yahoo/bard/webservice/data/config/names/DimensionName.java
  fili-core/src/main/java/com/yahoo/bard/webservice/data/config/names/FieldName.java
  fili-core/src/main/java/com/yahoo/bard/webservice/data/config/table/TableLoader.java
  fili-core/src/main/java/com/yahoo/bard/webservice/data/filterbuilders/DruidFilterBuilder.java
  fili-core/src/main/java/com/yahoo/bard/webservice/data/metric/mappers/ColumnMapper.java
  fili-core/src/main/java/com/yahoo/bard/webservice/data/volatility/VolatileIntervalsFunction.java
  fili-core/src/main/java/com/yahoo/bard/webservice/druid/client/SuccessCallback.java
  fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/HasDruidName.java
  fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/QueryType.java
  fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/postaggregation/PostAggregationType.java
  fili-core/src/main/java/com/yahoo/bard/webservice/logging/LogFormatter.java
  fili-core/src/main/java/com/yahoo/bard/webservice/metadata/QuerySigningService.java
  fili-core/src/main/java/com/yahoo/bard/webservice/table/availability/IsTableAligned.java
  fili-core/src/main/java/com/yahoo/bard/webservice/table/resolver/PhysicalTableResolver.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/MacroCalculationStrategies.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/RateLimiter.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/ResponseFormatResolver.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/ResponseStream.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/ResponseWriter.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/ResponseWriterSelector.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/handlers/workflow/RequestWorkflowProvider.java
  fili-navi/src/main/java/com/yahoo/bard/webservice/data/dimension/Tag.java
Labels: MERGEABLE

#655 Fix 'descriptionription' mis-naming in dimension field
  CHANGELOG.md
  docs/end-user-api.md
  fili-core/src/main/java/com/yahoo/bard/webservice/data/dimension/impl/KeyValueStoreDimension.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/DimensionsServlet.java
Labels: DEBUG, MERGEABLE

#651 Fix lookup metadata loader by pulling the RegisteredLookupDimension
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/application/AbstractBinderFactory.java
  fili-core/src/main/java/com/yahoo/bard/webservice/application/healthchecks/LookupHealthCheck.java
  fili-core/src/main/java/com/yahoo/bard/webservice/data/dimension/impl/LookupDimension.java
  fili-core/src/main/java/com/yahoo/bard/webservice/metadata/RegisteredLookupMetadataLoadTask.java
  fili-core/src/test/groovy/com/yahoo/bard/webservice/metadata/RegisteredLookupMetadataLoadTaskSpec.groovy
Labels: DEBUG, MERGEABLE
