Repository yahoo/fili, pull requests merged in 2018-07, with the labels that each got.

#722 Minor Improvements on Druid package
  fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/dimension/extractionfunction/ExtractionFunction.java
  fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/dimension/extractionfunction/ExtractionFunctionType.java
  fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/dimension/extractionfunction/PartialExtractionFunction.java
  fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/dimension/extractionfunction/RegularExpressionExtractionFunction.java
  fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/query/DruidFactQuery.java
  fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/query/DruidQuery.java
  fili-core/src/test/groovy/com/yahoo/bard/webservice/data/time/DefaultTimeGrainSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/druid/model/filter/SelectorFilterSpec.groovy
Labels: LOW HANGING, WIP

#727 Add support for "case_sensitive" attribute in FragmentSearchQuerySpec
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/query/FragmentSearchQuerySpec.java
  fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/query/InsensitiveContainsSearchQuerySpec.java
  fili-core/src/test/groovy/com/yahoo/bard/webservice/druid/model/query/FragmentSearchQuerySpecSpec.groovy
Labels: REVIEWABLE

#741 making custom sketch operation possible in PostAggregations
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/druid/util/FieldConverters.java
  fili-core/src/main/java/com/yahoo/bard/webservice/druid/util/ThetaSketchFieldConverter.java
  fili-core/src/test/groovy/com/yahoo/bard/webservice/data/config/metric/makers/MetricMakerSpec.groovy
Labels: MERGEABLE

#745 Change BaseCompositePhysicalTable to a concrete class.
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/table/BaseCompositePhysicalTable.java
  fili-core/src/main/java/com/yahoo/bard/webservice/table/MetricUnionCompositeTable.java
  fili-core/src/main/java/com/yahoo/bard/webservice/table/PartitionCompositeTable.java
  fili-core/src/main/java/com/yahoo/bard/webservice/table/availability/MetricUnionAvailability.java
Labels: MERGEABLE, TABLES

#742 Add injection point for handling exceptions
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/application/AbstractBinderFactory.java
  fili-core/src/main/java/com/yahoo/bard/webservice/exception/DataExceptionHandler.java
  fili-core/src/main/java/com/yahoo/bard/webservice/exception/FiliDataExceptionHandler.java
  fili-core/src/main/java/com/yahoo/bard/webservice/exception/FiliDimensionExceptionHandler.java
  fili-core/src/main/java/com/yahoo/bard/webservice/exception/FiliJobsExceptionHandler.java
  fili-core/src/main/java/com/yahoo/bard/webservice/exception/FiliMetricExceptionHandler.java
  fili-core/src/main/java/com/yahoo/bard/webservice/exception/FiliSlicesExceptionHandler.java
  fili-core/src/main/java/com/yahoo/bard/webservice/exception/FiliTablesExceptionHandler.java
  fili-core/src/main/java/com/yahoo/bard/webservice/exception/MetadataExceptionHandler.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/DimensionsApiRequest.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/JobsApiRequest.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/MetricsApiRequest.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/SlicesApiRequest.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/TablesApiRequest.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/DataServlet.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/DimensionsServlet.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/JobsServlet.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/MetricsServlet.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/SlicesServlet.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/TablesServlet.java
  fili-core/src/test/groovy/com/yahoo/bard/webservice/exception/FiliDataExceptionHandlerSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/exception/FiliDimensionExceptionHandlerSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/exception/FiliJobsExceptionHandlerSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/exception/FiliMetricExceptionHandlerSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/exception/FiliSlicesExceptionHandlerSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/exception/FiliTablesExceptionHandlerSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/endpoints/JobsServletReactiveChainforResultsEndpointSpec.groovy
Labels: MERGEABLE

#749 Allow the customer to control the test logging.
  CHANGELOG.md
  fili-core/src/test/java/com/yahoo/bard/webservice/application/JerseyTestBinder.java
Labels: MERGEABLE

#712 Refactor response code outof api request
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/data/HttpResponseChannel.java
  fili-core/src/main/java/com/yahoo/bard/webservice/data/HttpResponseMaker.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/DefaultResponseFormatType.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/FiliResponseWriterSelector.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/ResponseFormatType.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/ApiRequest.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/ApiRequestImpl.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/DataApiRequest.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/DataApiRequestFactory.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/DataApiRequestImpl.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/DefaultDataApiRequestFactory.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/DimensionsApiRequest.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/DimensionsApiRequestImpl.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/JobsApiRequestImpl.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/MetricsApiRequestImpl.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/ResponsePaginator.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/SlicesApiRequestImpl.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/TablesApiRequest.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/TablesApiRequestImpl.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/DataServlet.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/DimensionsServlet.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/EndpointServlet.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/FeatureFlagsServlet.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/JobsServlet.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/MetricsServlet.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/SlicesServlet.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/TablesServlet.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/handlers/DebugRequestHandler.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/handlers/PaginationRequestHandler.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/handlers/RequestContext.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/util/ResponseUtils.java
  fili-core/src/test/groovy/com/yahoo/bard/webservice/data/HttpResponseMakerSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/druid/model/query/WeightEvaluationQuerySpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/exception/FiliDimensionExceptionHandlerSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/exception/FiliMetricExceptionHandlerSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/exception/FiliTablesExceptionHandlerSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/DefaultResponseUtilsResolverSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/DimensionApiRequestMapperSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/FiliResponseWriterSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/JsonApiResponseWriterSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/ResponseWriterSelectorSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/TableFullViewProcessorSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/TablesApiRequestImplSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/UIJsonResponseSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/apirequest/ApiRequestSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/apirequest/DataApiRequestImplSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/apirequest/DimensionsApiRequestImplSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/apirequest/MetricsApiRequestImplSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/apirequest/SlicesApiRequestImplSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/apirequest/utils/TestingApiRequestImpl.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/apirequest/utils/TestingDataApiRequestImpl.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/endpoints/DebugDataServletSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/handlers/DebugRequestHandlerSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/responseprocessors/MappingResponseProcessorSpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/responseprocessors/ResultSetResponseProcessorSpec.groovy
Labels: CoreTeamReview, RESPONSE FORMAT, REVIEWABLE
