Repository yahoo/fili, pull requests merged in 2018-09, with the labels that each got.

#781 Removed miscellaneous deprecation
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/web/filters/BardLoggingFilter.java
Labels: MERGEABLE

#777 DimensionServlet refactor
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/web/endpoints/DimensionsServlet.java
Labels: DIMENSIONS, MERGEABLE

#789 Enforce role based security for incoming API requests
  CHANGELOG.md
  fili-security/src/main/java/com/yahoo/bard/webservice/web/security/RoleBasedTableValidatorRequestMapper.java
  fili-security/src/test/groovy/com/yahoo/bard/webservice/web/security/RoleBasedTableValidatorRequestMapperSpec.groovy
Labels: REVIEWABLE

#796 Ordering json fields of druid query before hashing them
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/util/Utils.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/handlers/CacheRequestHandler.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/handlers/CacheV2RequestHandler.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/handlers/EtagCacheRequestHandler.java
  fili-core/src/test/groovy/com/yahoo/bard/webservice/util/GroovyTestUtils.groovy
Labels: MERGEABLE
