Repository yahoo/fili, pull requests merged in 2019-04, with the labels that each got.

#562 Update API doc on performing constrained table queries
  docs/end-user-api.md
Labels: DOCS, MERGEABLE

#855 Add tests for IntervalUtils
  fili-core/src/test/groovy/com/yahoo/bard/webservice/util/IntervalUtilsSpec.groovy
Labels: MERGEABLE

#888 Make current macro align on the end of a target timezone
  CHANGELOG.md
  fili-core/src/main/java/com/yahoo/bard/webservice/config/BardFeatureFlag.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/DataApiRequestImpl.java
  fili-core/src/main/java/com/yahoo/bard/webservice/web/apirequest/binders/IntervalBinders.java
  fili-core/src/test/groovy/com/yahoo/bard/webservice/config/FeatureFlagRegistrySpec.groovy
  fili-core/src/test/groovy/com/yahoo/bard/webservice/web/apirequest/binders/IntervalBindersSpec.groovy
Labels: REVIEWABLE
